name: CI/CD with Docker

on: [push]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Tests
        run: |
          # Add your test commands here
          echo "Running tests..."

      - name: Build and Push Docker Image
        run: |
          chmod +x zapakiraj_27334.sh
          ./zapakiraj_27334.sh

      - name: Deploy Container
        run: |
          chmod +x zazeni_27334.sh
          ./zazeni_27334.sh
