name: Deploy na DockerHub

on: [push]

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repozitorija
        uses: actions/checkout@v2

      - name: Prijava v DockerHub
        uses: docker/login-action@v3
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Gradnja Docker slike
        run: docker build -t tomazsi/ghactionsarp .

      - name: Potisnitev slike v DockerHub
        run: docker push tomazsi/ghactionsarp
