name: Testiranje aplikacije

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Testiranje aplikacije
    runs-on: self-hosted
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repozitorija
        uses: actions/checkout@v2

      - name: Set up C++ environment
        uses: actions/setup-cpp@v2

      - name: Install dependencies
        run: sudo apt-get install -y libstdc++6

      - name: Build application
        run: g++ -o app main.cpp

      - name: Run tests
        run: ./test.sh
