name: Testiranje aplikacije

on: [push]

jobs:
  build-and-test:
    name: Testiranje aplikacije
    runs-on: self-hosted
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repozitorija
        uses: actions/checkout@v2

      - name: Install g++ and dependencies
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Install dependencies
        run: sudo apt-get install -y libstdc++6

      - name: Build application
        run: g++ -o app main.cpp

      - name: Run tests
        run: ./test.sh
