name: Deploy na DockerHub

on: [push]

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repozitorija
        uses: actions/checkout@v2

      - name: Prijava v DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Izvrši skripto za gradnjo Docker slike
        run: ./zapakiraj_27334.sh

      - name: Izvrši skripto za zagon vsebnika
        run: ./zazeni_27334.sh
