name: Deploy na DockerHub

on:
  workflow_run:
    workflows: ["Testiranje aplikacije "]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    needs: ${{ github.event.workflow_run.id }}
    steps:
      - name: Checkout repozitorija
        uses: actions/checkout@v2

      - name: Prijava v DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Gradnja Docker slike
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ime_slike .

      - name: Potisnitev slike v DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ime_slike
